sudo: required
services:
    - docker
    
before_install:
    - docker build -t cveach/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true cveach/react-test npm test
  
after_success:
    - docker build -t cveach/multi-client ./client
    - docker build -t cveach/multi-nginx ./nginx
    - docker build -t cveach/multi-server ./server
    - docker build -t cveach/multi-worker ./worker
    # Login to docker client
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Deploy images to docker hub
    - docker push cveach/multi-client
    - docker push cveach/multi-nginx
    - docker push cveach/multi-server
    - docker push cveach/multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-366855545907"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
  